<?php

return [
    'modules' => [
        'categories' => [
            'title' => 'Categories',
            'table' => 'categories',
            'order' => ['c.sort_order', 'asc'],
            'list' => ['name', 'description', 'catalog_count', 'listing_count', 'sort_order', 'status'],
            'form_help' => 'Organize product and supplier catalog flow with clean category management.',
            'fields' => [
                'name' => 'text',
                'slug' => 'text',
                'icon' => 'file',
                'description' => 'textarea',
                'accent_color' => 'color',
                'sort_order' => 'number',
                'status' => ['active', 'draft', 'archived'],
            ],
        ],
        'suppliers' => [
            'title' => 'Suppliers',
            'table' => 'suppliers',
            'order' => ['s.business_name', 'asc'],
            'list' => ['business_name', 'city', 'phone', 'product_count', 'minimum_order_amount', 'delivery_time', 'status'],
            'form_help' => 'Create supplier records according to the supplier app onboarding and business rules.',
            'fields' => [
                'business_name' => 'text',
                'owner_name' => 'text',
                'email' => 'email',
                'phone' => 'text',
                'city' => 'text',
                'address' => 'textarea',
                'latitude' => 'number',
                'longitude' => 'number',
                'minimum_order_quantity' => 'number',
                'minimum_order_amount' => 'number',
                'delivery_time' => 'text',
                'payment_terms' => 'text',
                'description' => 'textarea',
                'status' => ['pending', 'active', 'suspended'],
                'is_verified' => 'checkbox',
            ],
        ],
        'buyers' => [
            'title' => 'Buyers',
            'table' => 'buyers',
            'order' => ['b.store_name', 'asc'],
            'list' => ['store_name', 'buyer_name', 'phone', 'city', 'order_count', 'spend_total', 'status'],
            'form_help' => 'Create and manage retailer accounts for the buyer app.',
            'fields' => [
                'store_name' => 'text',
                'buyer_name' => 'text',
                'email' => 'email',
                'phone' => 'text',
                'city' => 'text',
                'address' => 'textarea',
                'latitude' => 'number',
                'longitude' => 'number',
                'preferred_language' => 'text',
                'status' => ['active', 'inactive', 'blocked'],
            ],
        ],
        'catalog_products' => [
            'title' => 'Catalog Products',
            'table' => 'catalog_products',
            'order' => ['cp.updated_at', 'desc'],
            'list' => ['name', 'category_name', 'packaging', 'unit_type', 'status'],
            'fields' => [
                'category_id' => 'number',
                'name' => 'text',
                'slug' => 'text',
                'emoji' => 'file',
                'description' => 'textarea',
                'packaging' => 'text',
                'unit_type' => 'text',
                'image_url' => 'file',
                'status' => ['active', 'draft', 'archived'],
            ],
        ],
        'offers' => [
            'title' => 'Offers',
            'table' => 'offers',
            'order' => ['o.updated_at', 'desc'],
            'list' => ['title', 'badge_label', 'supplier_name', 'product_name', 'offer_price', 'city', 'starts_at', 'status'],
            'form_help' => 'These cards appear in the buyer app home screen and can be limited to cities, suppliers, or products.',
            'fields' => [
                'title' => 'text',
                'description' => 'textarea',
                'badge_label' => 'text',
                'discount_label' => 'text',
                'image_url' => 'file',
                'supplier_id' => 'number',
                'supplier_product_id' => 'number',
                'catalog_product_id' => 'number',
                'offer_price' => 'number',
                'maximum_quantity' => 'number',
                'city' => 'text',
                'starts_at' => 'datetime',
                'ends_at' => 'datetime',
                'status' => ['active', 'draft', 'expired'],
            ],
        ],
        'products' => [
            'title' => 'Products',
            'table' => 'supplier_products',
            'order' => ['sp.updated_at', 'desc'],
            'list' => ['catalog_name', 'category_name', 'supplier_name', 'price', 'stock_quantity', 'min_order_qty', 'status'],
            'form_help' => 'Use the buyer and supplier app flow while managing the product listing and marketplace visibility.',
            'fields' => [
                'catalog_product_id' => 'number',
                'supplier_id' => 'number',
                'sku' => 'text',
                'price' => 'number',
                'stock_quantity' => 'number',
                'min_order_qty' => 'number',
                'min_order_amount' => 'number',
                'delivery_time' => 'text',
                'status' => ['active', 'draft', 'archived'],
                'is_featured' => 'checkbox',
            ],
        ],
        'notifications' => [
            'title' => 'Notifications',
            'table' => 'app_notifications',
            'order' => ['n.created_at', 'desc'],
            'list' => ['title', 'target_type', 'target_value', 'status', 'created_at'],
            'form_help' => 'Create announcements for all buyers, a specific city, or a single buyer account.',
            'fields' => [
                'title' => 'text',
                'message' => 'textarea',
                'target_type' => ['all', 'city', 'buyer'],
                'target_value' => 'text',
                'link_type' => 'text',
                'link_value' => 'text',
                'status' => ['active', 'draft', 'archived'],
            ],
        ],
        'orders' => [
            'title' => 'Orders',
            'table' => 'orders',
            'order' => ['o.order_date', 'desc'],
            'list' => ['order_number', 'store_name', 'business_name', 'item_count', 'total_amount', 'order_date', 'delivery_date', 'status'],
            'creatable' => false,
            'deletable' => false,
            'form_help' => 'Update fulfillment state and order notes according to supplier progress.',
            'fields' => [
                'order_number' => 'text',
                'buyer_id' => 'number',
                'supplier_id' => 'number',
                'status' => ['pending', 'processing', 'shipped', 'delivered', 'cancelled'],
                'payment_status' => ['pending', 'paid', 'failed', 'refunded'],
                'subtotal' => 'number',
                'delivery_fee' => 'number',
                'total_amount' => 'number',
                'notes' => 'textarea',
            ],
        ],
        'referral_claims' => [
            'title' => 'Referral Claims',
            'table' => 'buyer_referral_claims',
            'order' => ['c.created_at', 'desc'],
            'list' => ['referrer_store_name', 'referred_store_name', 'referral_code', 'reward_amount', 'status', 'created_at'],
            'creatable' => false,
            'editable' => false,
            'deletable' => false,
            'fields' => [
                'referrer_buyer_id' => 'number',
                'referred_buyer_id' => 'number',
                'referral_code' => 'text',
                'used_by_phone' => 'text',
                'reward_amount' => 'number',
                'referee_reward_amount' => 'number',
                'status' => ['completed', 'pending', 'cancelled'],
            ],
        ],
        'referral_codes' => [
            'title' => 'Referral Codes',
            'table' => 'buyer_referral_codes',
            'order' => ['rc.updated_at', 'desc'],
            'list' => ['referral_code', 'store_name', 'buyer_name', 'city', 'updated_at'],
            'creatable' => false,
            'editable' => false,
            'deletable' => false,
            'fields' => [
                'buyer_id' => 'number',
                'referral_code' => 'text',
            ],
        ],
        'chats' => [
            'title' => 'Chat Threads',
            'table' => 'chat_threads',
            'order' => ['t.last_message_at', 'desc'],
            'list' => ['store_name', 'business_name', 'subject', 'last_message', 'last_message_at'],
            'creatable' => false,
            'editable' => false,
            'deletable' => false,
            'fields' => [
                'buyer_id' => 'number',
                'supplier_id' => 'number',
                'subject' => 'text',
                'last_message' => 'textarea',
                'last_message_at' => 'datetime',
                'buyer_unread_count' => 'number',
                'supplier_unread_count' => 'number',
            ],
        ],
        'chat_messages' => [
            'title' => 'Chat Messages',
            'table' => 'chat_messages',
            'order' => ['created_at', 'desc'],
            'list' => ['thread_id', 'sender_type', 'sender_name', 'message_type', 'created_at'],
            'fields' => [
                'thread_id' => 'number',
                'sender_type' => ['buyer', 'supplier', 'admin'],
                'sender_name' => 'text',
                'message_body' => 'textarea',
                'message_type' => 'text',
            ],
        ],
        'devices' => [
            'title' => 'Buyer Devices',
            'table' => 'buyer_devices',
            'order' => ['d.updated_at', 'desc'],
            'list' => ['store_name', 'platform', 'firebase_token', 'updated_at'],
            'fields' => [
                'buyer_id' => 'number',
                'firebase_token' => 'textarea',
                'platform' => 'text',
            ],
        ],
        'otp_requests' => [
            'title' => 'OTP Requests',
            'table' => 'otp_requests',
            'order' => ['o.created_at', 'desc'],
            'list' => ['user_role', 'purpose', 'phone', 'provider', 'status', 'expires_at'],
            'fields' => [
                'user_role' => ['buyer', 'supplier'],
                'purpose' => ['login', 'register'],
                'phone' => 'text',
                'channel' => 'text',
                'provider' => 'text',
                'status' => ['pending', 'sent', 'verified', 'expired', 'superseded'],
                'expires_at' => 'datetime',
            ],
        ],
        'settings' => [
            'title' => 'Settings',
            'table' => 'settings',
            'order' => ['s.setting_key', 'asc'],
            'list' => ['setting_key', 'setting_value', 'setting_group', 'label'],
            'creatable' => false,
            'editable' => false,
            'deletable' => false,
            'fields' => [
                'setting_key' => 'text',
                'setting_value' => 'textarea',
                'setting_group' => 'text',
                'label' => 'text',
            ],
        ],
    ],
];
